### ISSUE TITLE
GUI for map builidng,

### ISSUE THREAD

**Issue by 0xMugen** [topology-foundation/counter-splash#13]
@0xNonCents Proposed A GUI for designing the map. This gives us overhead but potentially let's us have a real focus for game design. 

This will require some basic component design with(In order of priority)
- platforms 
- pain platforms(can go into paint mode) - maybe every platform is a paint platform tbd in testing.
- ladders
- jump pads
- paint brush items you can pick up?

**Comment by d-roak** [comment]
closing for archiving
