### ISSUE TITLE
CPU/Lag Spikes spikes when drawing

### ISSUE THREAD

**Issue by 0xNonCents** [topology-foundation/counter-splash#44]
Cpu latency maxes out and freezes the html canvas when drawing. We should investigate which code is causing lag.  ![Screenshot 2024-06-19 at 10 47 54 AM](https://github.com/topology-foundation/counter-splash/assets/25231247/207cbcda-7e25-4b4b-84a8-b64985ee81d2)   Note  Observed on my machine

**Comment by d-roak** [comment]
closing for archiving
