### ISSUE TITLE
Better movement

### ISSUE THREAD

**Issue by 0xMugen** [topology-foundation/counter-splash#5]
**Describe the problem you are trying to solve**
Movement is currently extremely basic. Having no speed ramping and instant reactions. 

**Describe the solution you'd like**
Testing out different accelerations and decelerations. Maybe adding a slide like in fps? Or B-hopping to cater towards the CS scene. 

**Describe alternatives you've considered**
Long slides with accumulable velocity Like in Titan fall / Apex legends?

Wall sliding is an other possibility. 

**Describe why the solution is optimal**
let's not reinvent the wheel focus on current proven methods

**Additional context**
https://www.gamedeveloper.com/design/analyzing-core-character-movement-in-3d

**Comment by d-roak** [comment]
closing for archiving
