### ISSUE TITLE
Arm model

### ISSUE THREAD

**Issue by 0xMugen** [topology-foundation/counter-splash#6]
**Describe the problem you are trying to solve**
As a first person game the arm model is important like seen here:
![image](https://github.com/topology-foundation/counter-splash/assets/45738409/81d05791-fb5a-4ac4-9288-23b03b3473f0)

We need to find good animations in tune with the world design we want to have.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe why the solution is optimal**

**Additional context**

**Comment by d-roak** [comment]
closing for archiving
