### ISSUE TITLE
Map design

### ISSUE THREAD

**Issue by 0xMugen** [topology-foundation/counter-splash#8]
Issue depends on "issue #5" completion

**Describe the problem you are trying to solve**

A game/level design problem woooo! Create a fun small map with some semi challenging parkour to acces certain parts of the wall. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe why the solution is optimal**

**Additional context**

**Comment by 0xMugen** [comment]
Because of issue #13 If we want to build a GUI let's limit this issue to simply making the basic design of the world (the lighting, the 3 other walls and maybe a spawn platform

**Comment by d-roak** [comment]
closing for archiving
